// have an array with 52 cards 
const deck = [
    { cardSuit: './images/spades.png', cardNumber: '2', cardValue: 2 },
    { cardSuit: './images/spades.png', cardNumber: '3', cardValue: 3 },
    { cardSuit: './images/spades.png', cardNumber: '4', cardValue: 4 },
    { cardSuit: './images/spades.png', cardNumber: '5', cardValue: 5 },
    { cardSuit: './images/spades.png', cardNumber: '6', cardValue: 6 },
    { cardSuit: './images/spades.png', cardNumber: '7', cardValue: 7 },
    { cardSuit: './images/spades.png', cardNumber: '8', cardValue: 8 },
    { cardSuit: './images/spades.png', cardNumber: '9', cardValue: 9 },
    { cardSuit: './images/spades.png', cardNumber: '10', cardValue: 10 },
    { cardSuit: './images/spades.png', cardNumber: 'J', cardValue: 10 },
    { cardSuit: './images/spades.png', cardNumber: 'Q', cardValue: 10 },
    { cardSuit: './images/spades.png', cardNumber: 'K', cardValue: 10 },
    { cardName: 13, cardSuit: './images/spades.png', cardNumber: 'A', cardValue: 11 },
    { cardSuit: './images/hearts.png', cardNumber: '2', cardValue: 2 },
    { cardSuit: './images/hearts.png', cardNumber: '3', cardValue: 3 },
    { cardSuit: './images/hearts.png', cardNumber: '4', cardValue: 4 },
    { cardSuit: './images/hearts.png', cardNumber: '5', cardValue: 5 },
    { cardSuit: './images/hearts.png', cardNumber: '6', cardValue: 6 },
    { cardSuit: './images/hearts.png', cardNumber: '7', cardValue: 7 },
    { cardSuit: './images/hearts.png', cardNumber: '8', cardValue: 8 },
    { cardSuit: './images/hearts.png', cardNumber: '9', cardValue: 9 },
    { cardSuit: './images/hearts.png', cardNumber: '10', cardValue: 10 },
    { cardSuit: './images/hearts.png', cardNumber: 'J', cardValue: 10 },
    { cardSuit: './images/hearts.png', cardNumber: 'Q', cardValue: 10 },
    { cardSuit: './images/hearts.png', cardNumber: 'K', cardValue: 10 },
    { cardName: 26, cardSuit: './images/hearts.png', cardNumber: 'A', cardValue: 11 },
    { cardSuit: './images/diamonds.png', cardNumber: '2', cardValue: 2 },
    { cardSuit: './images/diamonds.png', cardNumber: '3', cardValue: 3 },
    { cardSuit: './images/diamonds.png', cardNumber: '4', cardValue: 4 },
    { cardSuit: './images/diamonds.png', cardNumber: '5', cardValue: 5 },
    { cardSuit: './images/diamonds.png', cardNumber: '6', cardValue: 6 },
    { cardSuit: './images/diamonds.png', cardNumber: '7', cardValue: 7 },
    { cardSuit: './images/diamonds.png', cardNumber: '8', cardValue: 8 },
    { cardSuit: './images/diamonds.png', cardNumber: '9', cardValue: 9 },
    { cardSuit: './images/diamonds.png', cardNumber: '10', cardValue: 10 },
    { cardSuit: './images/diamonds.png', cardNumber: 'J', cardValue: 10 },
    { cardSuit: './images/diamonds.png', cardNumber: 'Q', cardValue: 10 },
    { cardSuit: './images/diamonds.png', cardNumber: 'K', cardValue: 10 },
    { cardName: 39, cardSuit: './images/diamonds.png', cardNumber: 'A', cardValue: 11 },
    { cardSuit: './images/clubs.png', cardNumber: '2', cardValue: 2 },
    { cardSuit: './images/clubs.png', cardNumber: '3', cardValue: 3 },
    { cardSuit: './images/clubs.png', cardNumber: '4', cardValue: 4 },
    { cardSuit: './images/clubs.png', cardNumber: '5', cardValue: 5 },
    { cardSuit: './images/clubs.png', cardNumber: '6', cardValue: 6 },
    { cardSuit: './images/clubs.png', cardNumber: '7', cardValue: 7 },
    { cardSuit: './images/clubs.png', cardNumber: '8', cardValue: 8 },
    { cardSuit: './images/clubs.png', cardNumber: '9', cardValue: 9 },
    { cardSuit: './images/clubs.png', cardNumber: '10', cardValue: 10 },
    { cardSuit: './images/clubs.png', cardNumber: 'J', cardValue: 10 },
    { cardSuit: './images/clubs.png', cardNumber: 'Q', cardValue: 10 },
    { cardSuit: './images/clubs.png', cardNumber: 'K', cardValue: 10 },
    { cardName: 52, cardSuit: './images/clubs.png', cardNumber: 'A', cardValue: 11 }
]


// TEST DECK - comment out main deck and deal test deck without shuffling 
// const deck = [
//     { cardName: 13, cardSuit: './images/spades.png', cardNumber: 'A', cardValue: 11 },
//     { cardName: 26, cardSuit: './images/hearts.png', cardNumber: 'A', cardValue: 11 },
//     { cardName: 39, cardSuit: './images/clubs.png', cardNumber: 'A', cardValue: 11 },
//     { cardSuit: './images/diamonds.png', cardNumber: 'K', cardValue: 10 },
//     { cardSuit: './images/hearts.png', cardNumber: '9', cardValue: 9 },
//     { cardSuit: './images/diamonds.png', cardNumber: 'Q', cardValue: 10 },
//     { cardSuit: './images/clubs.png', cardNumber: '8', cardValue: 8 }
// ]